services:
    app:
        build: .
        ports:
            - "3000:3000"
        command: npm start
        depends_on:
            - redis
    redis:
        image: redis:latest
        ports:
            - "6379:6379"