services:
  app:
    build: .
    container_name: express-app
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=express_app
    depends_on:
      - redis
      - postgres
    ports:
      - "3000:3000"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=userdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data: