apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: LoadBalancer
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: nowsiejko/service-a:latest 
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 500Mi
            cpu: "0.5"